import { make } from "vuex-pathify";

const state = () => ({
  messages: [],
  productsShow: [
    {
      buy: true,
      id: 62,
      name: "Smart TV",
      price: 1200,
      url: "https://www.dienmayxanh.com/may-doi-tra/tivi?prv=3",
    },
  ],
  allProducts: [
    { buy: true, id: 0, name: "person" },
    { buy: true, id: 1, name: "bicycle" },
    {
      buy: true,
      id: 2,
      name: "car",
    },
    { buy: true, id: 3, name: "motorbike" },
    { buy: true, id: 4, name: "aeroplane" },
    {
      buy: true,
      id: 5,
      name: "bus",
    },
    { buy: true, id: 6, name: "train" },
    { buy: true, id: 7, name: "truck" },
    {
      buy: true,
      id: 8,
      name: "boat",
    },
    { buy: true, id: 9, name: "traffic light" },
    { buy: true, id: 10, name: "fire hydrant" },
    {
      buy: true,
      id: 11,
      name: "stop sign",
    },
    { buy: true, id: 12, name: "parking meter" },
    { buy: true, id: 13, name: "bench" },
    {
      buy: true,
      id: 14,
      name: "bird",
    },
    { buy: true, id: 15, name: "cat" },
    { buy: true, id: 16, name: "dog" },
    {
      buy: true,
      id: 17,
      name: "horse",
    },
    { buy: true, id: 18, name: "sheep" },
    { buy: true, id: 19, name: "cow" },
    {
      buy: true,
      id: 20,
      name: "elephant",
    },
    { buy: true, id: 21, name: "bear" },
    { buy: true, id: 22, name: "zebra" },
    {
      buy: true,
      id: 23,
      name: "giraffe",
    },
    { buy: true, id: 24, name: "backpack" },
    { buy: true, id: 25, name: "umbrella" },
    {
      buy: true,
      id: 26,
      name: "handbag",
    },
    { buy: true, id: 27, name: "tie" },
    { buy: true, id: 28, name: "suitcase" },
    {
      buy: true,
      id: 29,
      name: "frisbee",
    },
    { buy: true, id: 30, name: "skis" },
    { buy: true, id: 31, name: "snowboard" },
    {
      buy: true,
      id: 32,
      name: "sports ball",
    },
    { buy: true, id: 33, name: "kite" },
    { buy: true, id: 34, name: "baseball bat" },
    {
      buy: true,
      id: 35,
      name: "baseball glove",
    },
    { buy: true, id: 36, name: "skateboard" },
    { buy: true, id: 37, name: "surfboard" },
    {
      buy: true,
      id: 38,
      name: "tennis racket",
    },
    { buy: true, id: 39, name: "bottle" },
    { buy: true, id: 40, name: "wine glass" },
    {
      buy: true,
      id: 41,
      name: "cup",
    },
    { buy: true, id: 42, name: "fork" },
    { buy: true, id: 43, name: "knife" },
    {
      buy: true,
      id: 44,
      name: "spoon",
    },
    { buy: true, id: 45, name: "bowl" },
    { buy: true, id: 46, name: "banana" },
    {
      buy: true,
      id: 47,
      name: "apple",
    },
    { buy: true, id: 48, name: "sandwich" },
    { buy: true, id: 49, name: "orange" },
    {
      buy: true,
      id: 50,
      name: "broccoli",
    },
    { buy: true, id: 51, name: "carrot" },
    { buy: true, id: 52, name: "hot dog" },
    {
      buy: true,
      id: 53,
      name: "pizza",
    },
    { buy: true, id: 54, name: "donut" },
    { buy: true, id: 55, name: "cake" },
    {
      buy: true,
      id: 56,
      name: "chair",
    },
    { buy: true, id: 57, name: "sofa" },
    { buy: true, id: 58, name: "pottedplant" },
    {
      buy: true,
      id: 59,
      name: "bed",
    },
    { buy: true, id: 60, name: "diningtable" },
    { buy: true, id: 61, name: "toilet" },
    {
      buy: true,
      id: 62,
      name: "Smart TV",
    },
    { buy: true, id: 63, name: "laptop" },
    { buy: true, id: 64, name: "mouse" },
    {
      buy: true,
      id: 65,
      name: "remote",
    },
    { buy: true, id: 66, name: "keyboard" },
    { buy: true, id: 67, name: "cell phone" },
    {
      buy: true,
      id: 68,
      name: "microwave",
    },
    { buy: true, id: 69, name: "oven" },
    { buy: true, id: 70, name: "toaster" },
    {
      buy: true,
      id: 71,
      name: "sink",
    },
    { buy: true, id: 72, name: "refrigerator" },
    { buy: true, id: 73, name: "book" },
    {
      buy: true,
      id: 74,
      name: "clock",
    },
    { buy: true, id: 75, name: "vase" },
    { buy: true, id: 76, name: "scissors" },
    {
      buy: true,
      id: 77,
      name: "teddy bear",
    },
    { buy: true, id: 78, name: "hair drier" },
    { buy: true, id: 79, name: "toothbrush" },
  ],
  selectedProds: [],
  hlsStart: null,
  hlsUrl: null,
  rtmpStart: null,
  timeCfgDelay: null,
  delayTime: null,
  pixelGroup: null,
  workerStart: null,
});

const getters = make.getters(state);

const actions = {};

const mutations = {
  ...make.mutations(state),
};

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations,
};
